### ISSUE TITLE
open_database error

### ISSUE THREAD

**Issue by BjoerndalM** [DHI/mikepluspy#39]
When trying to open a database i get the error:
SQLiteException: code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
Det angivne modul blev ikke fundet.
   ved DHI.Amelia.DataModule.Services.DataSource.DataSourceSpatiaLite.OpenDatabaseCore()
   ved DHI.Amelia.DataModule.Services.DataSource.BaseDataSource.OpenDatabase()

the code look like this:
from mikeplus import DataTableAccess
from pathlib import Path

sti_db = Path('C:\Users\......\Test.sqlite')
db = DataTableAccess(sti_db)

db_open = db.open_database()

The database has been made in a 2024 version of the mike+ program.

**Comment by wuwwen** [comment]
Dear @BjoerndalM , can you tell us the steps before you run the code? What install steps are you using. Thanks.

**Comment by BjoerndalM** [comment]
I am using the Spyder IDE, and running Python 3.9.7. 
Like i said, the MIKE+ installation is the 2024 version, but i have both the 2021 and 2023 version installed as well. (Could this be the issue?).
My windows os is Windows 10.0. 

The mikeplys libary was installed using the link:  https://github.com/DHI/mikepluspy/archive/refs/tags/v2024.0-latest.zip

**Comment by BjoerndalM** [comment]
I have tried uninstalling both the 2021 version and 2023 version of MIKE+, meaning i now only have the MIKE Urban 2020 version and MIKE+ 2024 version installed. 
The result, when trying to open the db, is the same, sadly

**Comment by wuwwen** [comment]
@BjoerndalM  I think the latest runtime error is not related to mikepluspy package. Please check this link as a reference. https://stackoverflow.com/questions/76214672/failed-to-initialize-python-runtime-dll#:~:text=To%20resolve%20this%2C%20go%20to%20the%20virtual%20environment,the%20python%20code%20again%20to%20see%20its%20working%21
About the first database problem, we will try hard to reproduce it. We have no success to reproduce for the time being.

**Comment by BjoerndalM** [comment]
Thank you wuwwen, i will check out the stackoverflow link.
Regarding the first problem, the database problem, i have noticed that i cant find the dll files for the DHI.Amelia.DataModule.Services, i only have the following:
![Skærmbillede 2024-06-11 123931](https://github.com/DHI/mikepluspy/assets/171819144/e01022b4-36ca-4ae3-b499-8a4b98388627)
The files are located at: C:\Program Files (x86)\DHI\MIKE+\2024\bin\x64

**Comment by BjoerndalM** [comment]
@wuwwen I tried following the stackoverflow link that you send me.
I still get the runtime error, but not before i run the script second time. 
The first time i run the scrip i get the following error message:
![image](https://github.com/DHI/mikepluspy/assets/171819144/20113195-5167-4a59-b5f6-2bd41c397eb9)

**Comment by wuwwen** [comment]
@BjoerndalM i think you are using the wrong version. 
If you installed MIKE+ 2024, please use this command to install mikepluspy:
pip install https://github.com/DHI/mikepluspy/archive/refs/tags/v2024.0-latest.zip

If you installed MIKE+ 2024 update 1, please use below way to install mikepluspy:
pip install https://github.com/DHI/mikepluspy/archive/refs/tags/v2024.1-latest.zip

Based on the error message, i think you have MIKE+ 2024 software installed, but used mikepluspy of 2024 update 1 version.

**Comment by BjoerndalM** [comment]
@wuwwen You were right about the mix up of versions, but using the correct version (MIKE+ 2024), means that i am back to the problem that i originally posted, regarding the missing DHI.Amelia.Services

**Comment by BjoerndalM** [comment]
@wuwwen I asked a colleague to tried to run the code, and he got the excact same error, about the missing files.
![image](https://github.com/DHI/mikepluspy/assets/171819144/01cc85fe-cbaa-4678-91fb-a589064163e3)

Like i said earlier, i dont have any files named DHI.Amelia.DataModule.Services.dll, neither does my colleague. 
I dont know if i am supposed to have that ?

**Comment by bemaDHI** [comment]
Hi @wuwwen, I encountered the same issue when trying to open the database.

Interestingly, I found that this issue only occurs if mikeio is also installed at the same time as mikepluspy. Uninstalling mikeio allows the database connection to open successfully.

Here are the details of my environment:
* Windows 11
* Python 3.12.3
* mikepluspy v2024.1-latest
* mikeio v2.0.1

Please let me know if you would like more details. Thanks!

**Comment by ecomodeller** [comment]
@bemaDHI Try to import mikecore instead of mikeio. I would assume that creates the same problem, but then at least we have narrowed down where this problem comes from.

**Comment by BjoerndalM** [comment]
@ecomodeller I managed to run the the open database function and run the model when not importing MIKEIO, 
if i then import MIKEIO the missing file exception reoccurs. The same is true when i import MIKECORE. 
So basicly i can run the model and manipulate the database, as long as i do not import MIKEIO or MIKECORE, which of course isnt ideal. 

I dont know if this help you narrow it down further.

**Comment by ecomodeller** [comment]
Thanks @BjoerndalM, this is clearly not ideal.

@JesperGr any thoughts on why this interference is happening?

**Comment by JesperGr** [comment]
mikecore-python and mikepluspy are both based on some common files. If they provide the same files in different versions, that can produce compatibility issues.

**Comment by BjoerndalM** [comment]
@ecomodeller Knowing the cause the issue is the first step. 
Is this something DHI will look into, or is it something i can fix on my own behalf or is it something i will just have to work around some way or another ?

**Comment by ecomodeller** [comment]
@BjoerndalM Not sure I will be of much help, since this problem is not really caused by Python, but conflicts of binary dependencies.

But if you describe the use case, where you need both `mikeio` and `mikepluspy` in the same script, I might be able to figure out a workaround🤔

**Comment by BjoerndalM** [comment]
@ecomodeller sure thing, we can give it a go !
Basicly the flow will be something along the lines of:

- Run simulation by using mikepluspy
- Read resultfile from simulation mikeio
- Make changes to sqlite fil, based on simulation result
- repeat until a certain criteria for the results are satisfied

So basicly the loop is: simulating (mikepluspy), reading results (mikeio) and changing the sqlite file (mikepluspy).

**Comment by JesperGr** [comment]
@BjoerndalM Just making sure: You are using mikeio only, and not mikeio1d for reading results? Because mikeio1d has a similar, larger, set of binary files.

**Comment by JesperGr** [comment]
For res1d files you will need mikeio1d. The mikeio and mikecore will not help there, as they are for the other dfs0+1+2+3+u result files. 

So, that means that you are up and running now then?

**Comment by BjoerndalM** [comment]
@JesperGr Yeah i dont think i necessarily need to manipulate any of the dfsX files. Or i can atleast work around that. 
So yeah i would say that i am up and running !

Thanks

**Comment by JesperGr** [comment]
@BjoerndalM Thanks for followup up.

@wuwwen We still need to investigate what causes the incompatibility with the mikecore-Python package and how to work around it, do you agree?

**Comment by wuwwen** [comment]
@JesperGr yes, I agree. I can have a look. But at least we should have a release version which all the DHI python package with the same version.

**Comment by JesperGr** [comment]
@wuwwen the mikeio1d package is able to pick up the required libraries from an external folder, e.g. you can point to a MIKE+ installation, and then it will use the files from there. That would work out for mikecore-python as well, I would guess.

**Comment by wuwwen** [comment]
@JesperGr mikepluspy already pointed into the installation. It has used MikeImport.Setup() method to point to the correct version installation location. Did latest mikeio1d using the mike update 1 binaries? If it is, it must can work with latest mikepluspy.

**Comment by pawelhar** [comment]
Hi! Not sure if this a related problem but I am getting the following problem when trying to open a database:

Using mikeplus installed using pip install mikeplus==2024.1.* and Mike+ version 2024 Update 1 on Windows 11
simply running:
from mikeplus import DataTableAccess
data_access = DataTableAccess("C:/Users...Test.sqlite")
data_access.open_database()
System.IO.FileLoadException: Det krävs en sammansättning med ett starkt namn. (Undantag från HRESULT: 0x80131044)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python311\site-packages\mikeplus\datatableaccess.py", line 74, in open_database
    data_source.OpenDatabase()
System.IO.FileLoadException: Det går inte att läsa in filen eller sammansättningen System.Data.SQLite, Version=1.0.113.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139 eller ett av dess beroenden. Det krävs en sammansättning med ett starkt namn. (Undantag från HRESULT: 0x80131044)
Filnamn: System.Data.SQLite, Version=1.0.113.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139 ---> System.IO.FileLoadException: Det krävs en sammansättning med ett starkt namn. (Undantag från HRESULT: 0x80131044)
   vid DHI.Amelia.DataModule.Services.DataSource.DataSourceSpatiaLite.OpenDatabaseCore()
   vid DHI.Amelia.DataModule.Services.DataSource.BaseDataSource.OpenDatabase()

**Comment by wuwwen** [comment]
@pawelhar This issue happens when you have several version of System.Data.Sqlite avalaible in your pc. Can you please check where you are trying load the System.Data.Sqlite? You can use ProcessExplorer to check the location of the loaded binaries.

**Comment by dantzert** [comment]
The issue with importing the Amelia dll files here and in https://github.com/DHI/mikepluspy/issues/33 may be an architectural incompatibility. That is, the system finds 32-bit dlls and tries to use them while on a 64 bit machine. 

When I had
os.environ["PATH"] += r";C:\Program Files (x86)\DHI\MIKE+\2024\bin" 

I got those "could not find" errors. As there's an x86 in the filepath, I'm thinking these may be 32-bit dlls. When I change to

os.environ["PATH"] += r";C:\Program Files (x86)\DHI\MIKE+\2024\bin\x64"  

things are working for me now and I'm able to open the database and run a simulation with the Sirius example project. 

The snippet below might be necessary, but I'm not sure yet:

# Path to the folder containing the DLLs
dll_folder = r"C:\\Program Files (x86)\\DHI\\MIKE+\\2024\\bin\\x64"

# List all files in the folder
dll_files = [f for f in os.listdir(dll_folder) if f.endswith(".dll")]

# Check if each DLL can be loaded
for dll_file in dll_files:
    dll_path = os.path.join(dll_folder, dll_file)
    try:
        ctypes.CDLL(dll_path)
        #print(f"{dll_file} loaded successfully.")
    except OSError as e:
        print(f"Failed to load {dll_file}: {e}")


Please let me know if you'd like additional context on this.
